---
- name: Disable SELinux
  selinux:
    state: disabled

- name : Install the lastest version of Apache
  yum:
    name=httpd
    state=latest

- name: Start Apache service
  service:
    name=httpd
    state=started
    enabled=true

- name: Check Apache service
  command: systemctl status httpd
  args:
    warn: false

- name: Virutal host configuration 1/3
  file:
    path: /var/www/{{ user_web }}/public_html
    state: directory
    mode: 0755

- name: Virutal host configuration 2/3
  file:
    path: /var/www/{{ user_web }}/public_html
    owner: apache
    group: apache

- name: Virutal host configuration 3/3
  file:
    path: /var/www/
    mode: 0755

- name: Create first web page
  copy: src={{ item.0 }} dest={{ item.1 }}
  with_together:
    - [ '{{ Source_1 }}', '{{ Source_2 }}' ]
    - [ '{{ Destination_1 }}', '{{ Destination_2 }}' ]


- name : Create files for Virtual Host Files
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sitesavailable }}"
    - "{{ sitesenabled }}"

- name: Update htttp.conf file
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    block: IncludeOptional sites-enabled/*.conf

- name: Edit Virital Hosts files
  file:
    path: /etc/httpd/sites-available/{{ user_web }}.conf
    state: touch

- name: Update htttp.conf file
  blockinfile:
    path: /etc/httpd/sites-available/{{ user_web }}.conf
    block: |
      <VirtualHost *:80>
      ServerName www.{{ user_web }}/.com
      ServerAlias {{ user_web }}/
      DocumentRoot /var/www/{{ user_web }}/public_html
      ErrorLog /var/www/{{ user_web }}/error.log
      CustomLog /var/www/{{ user_web }}/requests.log combined
      </VirtualHost>

- name : Create symbolic link
  command : sudo ln -s /etc/httpd/sites-available/{{ user_web }}.conf /etc/httpd/sites-enabled/{{ user_web }}.conf

- name: Restart apache
  service:
    name: httpd
    state: restarted
