# file: /roles/tasks/zabbix-client/01_install.yml
---
#- name: Update system
#  yum: name=* state=latest
- name: Install new zabbix repository
  yum:
    name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
    state: present

- name: Install Zabbix agent
  yum: name=zabbix-agent state=latest
