# file: roles/mysql/tasks/01_install.yml
---

- name: MySql packages are installed
  yum: name={{ item }}
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python

- name: Start MySQL service
  service: name=mariadb state=started enabled=true
