# file: roles/mysql/tasks/02_configure.yml
---
- name: Set the root password for all root accounts
  mysql_user: name=root host=localhost password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  #when: ansible_hostname != 'localhost'

- name: Configure MySql for easy access as root user
  template: src=.my.cnf.j2 dest=~/.my.cnf owner=root group=root mode=0644
  #/root/.my.cnf

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host=* state=absent
