# file: roles/zabbix/tasks/01_install.yml
---
- name : Install epel repository
  yum: name=epel-release state=latest

- name: Update system
  yum: name=* state=latest

- name: Install new zabbix repository
  yum:
    #name: http://repo.zabbix.com/zabbix/2.2/rhel/7/x86_64/zabbix-release-2.2-1.el7.noarch.rpm
    name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
    state: present

- name: Install Zabbix, Zabbix agent, Zabbix web interface, Apache2, MariaDB, PHP, phpMyAdmin
  yum: name={{ item }} state=latest
  with_items :
      - zabbix-server-mysql
      - zabbix-agent
      - zabbix-web-mysql
      - mysql
      - mariadb-server
      - httpd
      - php
      - MySQL-python
      - phpmyadmin
